from typing import Callable, Protocol, ClassVar
from typing_extensions import TypeAlias, Type

class WindowLike(Protocol):
    def __init__(self, window_manager: WindowManagerLike, id: str) -> None: ...
    def get_name(self) -> str: ...
    def get_position(self) -> tuple[int, int]: ...
    def get_size(self) -> tuple[int, int]: ...
    def click(self, x: int, y: int, button: str, duration: float = 0.09, bypass_out_of_bounds_check: bool = False): ...
    def key_down(self, key: str): ...
    def key_up(self, key: str): ...
    def press(self, key: str, duration: float): ...
    def typewrite(self, text: str, hold_duration: float = 0.09, spacing_duration: float = 0): ...

class GetWindowFn(Protocol):
    def __call__(self, name: str) -> WindowLike: ...

class WindowManagerLike(Protocol):
    def get_name_of_window(self, id: str) -> str: ...
    def get_position_of_window(self, id: str) -> tuple[int, int]: ...
    def get_size_of_window(self, id: str) -> tuple[int, int]: ...
    def click(self, x: int, y: int, duration: float | int, button: str): ...
    def mouse_down(self, button: str): ...
    def mouse_up(self, button: str): ...
    def key_down(self, key: str): ...
    def key_up(self, key: str): ...
    def press(self, key: str, duration: float): ...
    def typewrite(self, text: str, hold_duration: float = 0.09, spacing_duration: float = 0): ...

WindowLikeType: TypeAlias = Type[WindowLike]
'''WindowLike but for un-instantiated references and such'''